var formula = [];
formula.push({topic: 1.111,  word: "単項式の定義", text: "数や文字およびそれらの積として表される式を単項式という。<p>単項式において, かけ合わされている文字の個数をその次数という。</p><p>また, 単項式の数の部分をその係数という。</p>"});
formula.push({topic: 1.112,  word: "多項式・整式の定義", text: "<p>単項式の和として表される式を多項式という。</p><p>単項式と多項式を合わせて整式と呼ぶ。</p><p>整式を整理したとき, その中で最も次数が高い単項式の次数をその次数と定める。</p><p>また，整式において文字を含まない項を定数項といい，文字の部分が同じである項を同類項と呼ぶ。</p>"});
formula.push({topic: 1.113,  word: "降べき・昇べきの順", text: "特定の文字に着目するとき，整式の項が次数の高い順に並んでいることを「降べきの順」という。<p>同様に，次数の低い順に並んでいることを「昇べきの順」という。</p>"});
formula.push({topic: 1.114,  word: "累乗", text: "同じ数をいくつもかけ合わせること。<p>または，その積。</p>"});
formula.push({topic: 1.115,  word: "指数法則 (数学 I )", text: "$m,~n$ が正の整数のとき,\\begin{align}a^m\\cdot a^n&=a^{m+n},\\\\(a^m)^n&=a^{mn},\\\\(ab)^m&=a^m\\cdot b^m.\\end{align}" });
formula.push({topic: 1.116, word: "因数分解", text: "整式を $1$ 次以上のいくつかの整式の積の形に表すこと．<p>このとき，積をなす各整式をもとの整式の因数という．</p>"});
formula.push({topic: 1.117,  word: "２次の乗法公式", text: "<div><ol><li>$(a+b)^2=a^2+2ab+b^2$ </li><li>$(a-b)^2=a^2-2ab+b^2$</li><li>$(a+b)(a-b)=a^2-b^2$ </li><li>$(x+a)(x+b)=x^2+(a+b)x+ab$ </li><li>$(ax+b)(cx+d)=acx^2+(ad+bc)x+bd$ </li></ol></div>"});
formula.push({topic: 1.120 ,  word: "整数・自然数の定義", text: "０と，０に１ずつ加えていって得られる数と，０から１ずつ引いていって得られる数を合わせて「整数」という。<p>正の整数を「自然数」という。</p>"});
formula.push({topic: 1.121, word: "小数の定義", text: "実数を，小数点を用いて表したものを「小数」という．<p>小数点以下の桁数が有限である小数を「有限小数」，小数点以下の桁数が無限である小数を「無限小数」という．</p>無限小数のうち，ある位以下が同じ数字の並びで繰り返されるものを「循環小数」という．"});
formula.push({topic: 1.122, word: "実数の定義", text: "整数および有限小数，無限小数で表される数を合わせて「実数」という．"});
formula.push({topic: 1.123 ,  word: "有理数・無理数の定義", text: "整数 $a$ と０でない整数 $b$ を用いて $\\frac{a}b$ と表すことのできる数を「有理数」という．<p>また，有理数でない実数を「無理数」という．</p><p>すなわち，実数は有理数と無理数からなる．</p>"});
formula.push({topic: 1.124,  word: "既約分数の定義", text: "それ以上約分できない分数。"});
formula.push({topic: 1.125,  word: "絶対値の定義・性質", text: "実数 $a$ に対して，数直線上で点 $\\mr{O}$ から点 $\\mr{A}(a)$ までの距離を 「$a$ の絶対値」といい, $|a|$ で表す。<p>一般に, 次が成り立つ。</p><ol><li>$a\\geqq 0$ のとき，$|a|=a$ </li><li>$a< 0$ のとき，$|a|=-a$ </li></ol>$a,~b$ を実数とすると<ol><li>$|a|\\geqq0$</li><li>$|-a|=|a|$</li><li>$|a|^2=a^2$</li><li>$|ab|=|a||b|$</li><li>$\\left|\\bun{a}{b}\\right|=\\bun{|a|}{|b|}$ ただし，$b\\ne0$</li></ol>"});
formula.push({topic: 1.127, word: "平方根の定義", text: "実数 $a$ に対して，$2$ 乗すると $a$ になる数を 「 $a$ の平方根」という．<p>$a < 0$ のとき，$a$ の平方根は存在しない．</p><p>$a > 0$ のとき，$a$ の平方根は $2$ つ存在し，そのうち正の値を $\\rt a~$，負の値を $-\\rt a$ と表す．</p><p>$a = 0$ のとき，$a$ の平方根は $0$ だけである．つまり，$\\rt0=0.$</p>"});
formula.push({topic: 1.128, word: "平方根の性質", text: "実数 $a$ に対して，\\[\\rt{a^2}=|a|.\\]$a > 0,~b > 0$ のとき，\\begin{align}&\\rt{ab}=\\rt a \\rt b,\\\\&\\rt{\\bun ab} =\\bun{\\rt a}{\\rt b}.\\end{align}"});
formula.push({topic: 1.129, word: "有理化", text: "根号を含む式を，根号を含まない式に変形することを「有理化」という．"});
formula.push({topic: 1.130, word: "整数部分，小数部分", text: "実数 $a$ に対して，$a$ 以下の最大の整数を「 $a$ の整数部分」という．<p>$a$ の整数部分を $n$ とするとき，$a-n$ を「 $a$ の小数部分」という．</p>"});
formula.push({topic: 1.131, word: "二重根号", text: "$a >0,~b>0$ のとき，\\[\\rt{a+b+2\\rt{ab}}=\\rt a +\\rt b.\\]$a > b > 0$ のとき，\\[\\rt{a+b-2\\rt{ab}}=\\rt a -\\rt b.\\] "});
formula.push({topic: 1.132,  word: "不等式の性質", text: "<div>\\begin{align}&1.~a>b,~b>c ~\\Rightarrow~ a>c\\\\&2.~a>b~\\Rightarrow~ a+c>b+c,~a-c>b-c\\\\&3.~a>b,~c>0 ~\\Rightarrow~ ac>bc,~\\bun{a}c>\\bun{b}c\\\\&4.~a>b,~c<0 ~\\Rightarrow~ ac< bc,~\\bun{a}c<\\bun{b}c\\end{align}</div>"});
formula.push({topic: 1.133, word: "絶対値と方程式・不等式", text: "$a >0$ のとき， <ol><li>$|x|=a\\iff x=\\pm a$ </li><li>$|x|< a\\iff -a< x < a$</li><li>$|x| > a \\iff x<-a~または~a< x$</li></ol>"});
formula.push({topic: 1.134, word: "対称式と交代式", text: "ある式において，$a$ と $b$ をとりかえても元と変わらないとき，その式を「 $a,~b$ についての対称式」という．<p>$a,~b$ についての対称式は，基本対称式 $a+b, ~ab$ のみで表すことができる．<p>ある式において，$a$ と $b$ をとりかえると元の式の $-1$ 倍になるとき，その式を「 $a,~b$ についての交代式」という．</p><p>$a,~b$ についての交代式は， $a,~b$ についての対称式と $a-b$ の積で表すことができる．</p>"});
formula.push({topic: 1.201, word: "集合と要素", text: "<p>ある条件を満たすもの全体の集まりを「集合」といい，$A,~B$ などの文字で表す． </p><p>集合をなす個々のものを，その集合の「要素」という．</p><p>$a$ が集合 $A$ の要素であるとき，「 $a$ は集合 $A$ に属する」といい，$a \\in A$ と表す．</p><p>また，$b$ が集合 $A$ の要素でないことを $b\\notin A$ と表す．</p>"});
formula.push({topic: 1.202, word: "集合の表し方", text: "集合の表し方には，<ol type ='i'><li>要素を列挙する方法</li><li>要素の条件を述べる方法</li></ol>がある．<p>例えば，$15$ の正の約数全体の集合を $A$ とする．</p><p>i. によると\\[A=\\{1,~3,~5,~15\\},\\]</p><p>ii. によると\\[A=\\{x~|~x~は15の正の約数\\}\\]と表される．</p>"});
formula.push({topic: 1.203, word: "部分集合と集合の相等", text: "集合 $A$ のすべての要素が集合 $B$ にも属すとき，つまり\\[x \\in A ならば x \\in B\\]であるとき，「$A$ は $B$ に含まれる」といい，\\[A \\subset B\\]と表す．<p>このとき，$A$ を $B$ の「部分集合」という．<p>$A$ と $B$ の要素が全て一致しているとき，「集合 $A,~B$ は等しい」といい，\\[A=B\\] と表す．</p>"});
formula.push({topic: 1.204, word: "共通部分と和集合", text: "集合 $A,~B$ のどちらにも属する要素全体の集合を 「$A$ と$B$ の共通部分」といい，\\[A \\cap B\\]で表す．<p>また，$A,~B$ の少なくとも一方に属する要素全体の集合を「$A$ と $B$ の和集合」といい，\\[A\\cup B\\]で表す．</p>"});
formula.push({topic: 1.205, word: "空集合", text: "要素をもたない集合を「空集合」といい，$\\varnothing$ で表す．<p>どのような集合 $A$ についても，空集合は $A$ の部分集合である．つまり，\\[\\varnothing \\in A\\]である．</p>"});
formula.push({topic: 1.206, word: "全体集合と補集合", text: "何らかの集合を考える際に，対象にするもの全体を要素とする集合を「全体集合」といい，$U$ などと表す．<p>全体集合 $U$ の部分集合 $A$ に対して， $U$の要素で $A$ に属さないもの全体の集合を $A$ の「補集合」といい，$\\overline{A}$ で表す．</p>"});
formula.push({topic: 1.207, word: "ド・モルガンの法則 (集合)", text: "集合 $A,~B$ について，次が成り立つ．\\begin{align}&\\overline{A \\cup B}=\\overline A ~\\cap~\\overline B,\\\\&\\overline{A \\cap B}=\\overline A ~\\cup~\\overline B\\end{align}"});
formula.push({topic: 1.208, word: "命題と条件", text: "正しいか否かが定まる文や式を「命題」という．<p>命題が正しいとき，その命題は「真である」という．</p><p>命題が正しくないとき，その命題は「偽である」という．</p>変数を含む文や式で，その変数に値を代入したときに真偽が定まるものを「条件」という．"});
formula.push({topic: 1.2085, word: "命題と条件の否定", text: "命題 $A,~B$ について，<p>$A$ が成立するとき，$B$ は成り立たず，</p><p>$A$ が成立しないとき，$B$ は成り立つ</p>という関係にあるとき，$B$ を $A$ の「否定」といい， $\\overline{A}$ と表す．<p>また，変数 $x$ に関する条件 $p,~q$ があり，任意の変数 $x$ について，<p>$p$ が成立するとき，$q$ は成り立たず，</p><p>$p$ が成立しないとき，$q$ は成り立つ</p>という関係にあるとき，$q$ を $p$ の「否定」といい， $\\overline{~p~}$ と表す．<p>$p$ を満たすものの集合を $P$ とすると，$\\overline{~p~}$ を満たすものの集合はその補集合 $\\overline{P}$ である．</p> </p>"});
formula.push({topic: 1.209, word: "「ならば」の命題", text: "条件 $p,~q$ に対して，「 $p$ ならば $q$ である」という命題を\\[p \\Longrightarrow q\\]と表す．<p>$p,~q$ を満たすものの集合をそれぞれ $P,~Q$ で表すとき，「 $p \\Longrightarrow q$ 」が真であるとは $P \\subset Q$ が成り立つことである．</p> また，「 $p \\Longrightarrow q$ 」，「 $q \\Longrightarrow p$ 」がともに真であるとき，\\[p\\iff q\\]と表し，これは $P=Q$ が成り立つことに等しい．"});
formula.push({topic: 1.210, word: "必要条件と十分条件", text: "条件 $p,~q$ に対して，命題「 $p \\Longrightarrow q$ 」が成り立つとき，<p>$p$ は $q$ であるための十分条件である，</p><p>$q$ は $p$ であるための必要条件である</p>という．<p>命題「 $p \\iff q$ 」が成り立つとき，<p>$p$ は $q$ であるための必要十分条件である，</p>または，<p>$p$ と $q$ は同値である</p>という．</p>"});
formula.push({topic: 1.211, word: "ド・モルガンの法則 (条件)", text: "条件 $p,~q$ に対し，次が成り立つ．\\begin{align}&\\overline{p かつ q}\\iff\\overline{~p~} または \\overline{~q~},\\\\&\\overline{p または q}\\iff\\overline{~p~} かつ \\overline{~q~}.\\end{align}"});
formula.push({topic: 1.212, word: "逆，裏，対偶", text: "命題「 $p \\Longrightarrow q$ 」$\\cdots (*)$ に対して，<p> 「 $q \\Longrightarrow p$ 」を $(*)$ の逆,</p><p> 「 $\\overline{~p~} \\Longrightarrow \\overline{~q~}$ 」を $(*)$ の裏,</p><p> 「 $\\overline{~q~} \\Longrightarrow \\overline{~p~}$ 」を $(*)$ の対偶</p>という．<p>$(*)$ と $(*)$ の対偶は真偽が一致する．</p>"});
formula.push({topic: 1.213, word: "背理法", text: "ある命題が成り立たないと仮定すると矛盾が生じることを導いて，その命題の成立を証明する論法を「背理法」という．"});
formula.push({topic: 1.214, word: "ド・モルガンの法則 (すべて・ある)", text: "$x$ に関する条件 $p$ にたいして，<p>「すべての $x$ について $p$ 」</p>の否定は <p>「ある $x$ について $\\overline{~p~}$ 」．</p> <p>「ある $x$ について $p$ 」</p> の否定は<p>「すべての $x$ について $\\overline{~p~}$ 」.</p> "});
formula.push({topic: 1.301, word: "関数，定義域，値域，最大値・最小値", text: "$2$ つの変数 $x,~y$ があり，$x$ の値に応じて $y$ の値がただ $1$ つに定まるとき，<p>「 $y$ は $x$ の関数である」</p>といい，\\[y=f(x),~y=g(x)\\]などと表す．<p>関数 $y=f(x)$ において，$x$ の値 $a$ に対する関数 $y$ の値を $f(a)$ と表す．</p><p>関数 $y=f(x)$ について，</p><p>$x$ のとり得る値の範囲を「定義域」といい，\\[y=f(x)~~(a \\leqq x \\leqq b)\\]などと表す．</p><p>また，$y$ のとり得る値の範囲を「値域」という．</p><p>定義域について言及がないときは，式 $f(x)$ が意味をもつような $x$ の値全体を定義域と考える．</p><p>値域に最大の値，最小の値があるとき，それぞれを関数 $y=f(x)$ の「最大値」,「最小値」という．</p>"});
formula.push({topic: 1.302, word: "座標平面", text: "座標軸の定められた平面を「座標平面」という．<p>座標平面上の点 $\\mr P$ の位置は，次の図のように，実数の組 $(a,~b)$ で表される．</p>この組を点 $\\mr P$ の「座標」といい，\\[\\mr P(a,~b)\\]と表す．", canvasScript: "start=[-0.5,-0.5];end=[3,2];baseFont=' 25px serif ';drawAxis();pointA=[2,1];pointB=[2,0];pointC=[0,1];pointMark({points:[[pointA, 'P(a, b)',[0.5,0.5]]],color:'red',size:2});drawAxisHoot({from:pointA,stringX:'a',stringXmove:[-0.5,-1.5],stringY:'b',stringYmove:[-1.5,-0.5]});verticalMark({at:pointB,to:pointA,size:2});verticalMark({at:pointC,to:[0,0],size:2});"});
formula.push({topic: 1.303, word: "象限", text: "座標平面は座標軸によって $4$ つの部分に分けられる．<p>これらを次の図のように，第 $1$ 象限，第 $2$ 象限，第 $3$ 象限，第 $4$ 象限という．</p>ただし，座標軸はどの象限にも含まれないものとする．", canvasScript: "start=[-3,-3];end=[3,3];baseFont=' 25px serif ';drawAxis();putString({at:[0.7,1.7],string:'第１象限',color:'red'});putString({at:[0.7,1.2],string:'(正，正)',color:'red'});putString({at:[-2.5,1.7],string:'第２象限',color:'blue'});putString({at:[-2.5,1.2],string:'(負，正)',color:'blue'});putString({at:[-2.5,-1.2],string:'第３象限',color:'red'});putString({at:[-2.5,-1.7],string:'(負，負)',color:'red'});putString({at:[0.7,-1.2],string:'第４象限',color:'blue'});putString({at:[0.7,-1.7],string:'(負，負)',color:'blue'});"});
formula.push({topic: 1.304, word: "関数のグラフ", text: "関数 $y=f(x)$ において，$x$ の値とそれに対応する $y$ の値の組 $(x,~y)$ を座標とする点全体からなる図形を<p>「 $y=f(x)$ のグラフ」</p>という．"});
formula.push({topic: 1.305, word: "$2$ 次関数の定義", text: "$y$ が定数 $a,~b,~c$ を用いて\\[y=ax^2+bx+c~~(a\\ne0)\\]の形で表されるとき，つまり $y$ が $x$ の $2$ 次式であるとき，<p>「 $y$ は $x$ の $2$ 次関数である」</p>という． "});
formula.push({topic: 1.306, word: "$y=ax^2$ のグラフ ", text: "$2$ 次関数 $y=ax^2$ のグラフが表す曲線を「放物線」という．<p>一般に，放物線は対称軸をもち，それを放物線の「軸」といい，軸と放物線の交点を「頂点」という．</p>下図の通り，放物線 $y=ax^2$ の軸は $y$ 軸であり，頂点は原点である．<p>また，この放物線は</p><p>$a > 0$ のとき，下に凸，</p><p>$a < 0$ のとき，上に凸</p>であるという．", canvasScript: "start=[-5,-5];end=[5,5];drawAxis();function ff(x){return 0.4*x*x;};drawGraph({func:ff,color:'red',width:2});function gg(x){return -0.4*x*x;};drawGraph({func:gg,color:'blue',width:2});putString({at:[3,2],string:'y=ax^2',color:'red'});putString({at:[3,1.4],string:'(a > 0)',color:'red'});putString({at:[3,-1],string:'y=ax^2',color:'blue'});putString({at:[3,-1.5],string:'(a < 0)',color:'blue'});"});
formula.push({topic: 1.307, word: "$y=a(x-p)^2+q$ のグラフ", text: "2 次関数\\[\\bm{y=a(x-p)^2+q}\\]のグラフは $y=ax^2$ のグラフを <p>$x$ 軸方向に $p$，$y$ 軸方向に $q$ </p>だけ平行移動した放物線である．<p>その軸は直線 $\\bm{x=p}$，頂点は $\\bm{(p,~q)}$ である．</p>", canvasScript: "start=[-3,-2];end=[9,7];drawAxis();function ff(x){return 0.4*(x-3)*(x-3)+1.5;};drawGraph({func:ff,color:'red',width:2});function gg(x){return 0.4*x*x;};drawGraph({func:gg,lineDash:3,width:1});putString({at:[4.5,2],string:'y=a(x-p)^2+q',color:'red'});putString({at:[1,5.5],string:'y=ax^2'});pointO=[0,0];pointA=[3,0];pointB=[3,1.5];drawAxisHoot({from:pointB,stringX:'p',stringXmove:[0,-1.5],stringY:'q',stringYmove:[-1.5,-0.5]});drawHenko({from:pointO,to:pointA,arrow:true,angle:55,string:'p',color:'blue'});drawHenko({from:pointA,to:pointB,arrow:true,angle:60,string:'q',color:'blue'});"});
formula.push({topic: 1.308, word: "平方完成", text: "$ax^2+bx+c$ を $a(x-p)^2+q$ の形にすることを「平方完成」という．<p>次の公式を用いるとよい．</p>\\begin{align}&x^2+2Ax=(x+A)^2-A^2,\\\\&x^2-2Ax=(x-A)^2-A^2\\end{align}"});
formula.push({topic: 1.309, word: "$y=ax^2+bx+c$ のグラフ", text: "$2$ 次関数 $y=ax^2+bx+c$ のグラフは，$y=ax^2$ のグラフを平行移動したグラフで，<p>軸は直線 $x=-\\bun{b}{2a}$，</p><p>頂点は点 $\\left(-\\bun{b}{2a},~-\\bun{b^2-4ac}{4a}\\right)$.</p>"});
formula.push({topic: 1.310, word: "グラフの平行移動", text: "一般に，関数 $y=f(x)$ のグラフを<p>$x$ 軸方向に $p$，$y$ 軸方向に $q$</p> だけ平行移動したグラフは関数\\[y-q=f(x-p)\\]つまり，\\[y=f(x-p)+q\\]のグラフとなる．"});
formula.push({topic: 1.311, word: "グラフの対称移動", text: "<p>一般に，関数 $y=f(x)$ のグラフを $x$ 軸に関して対称移動すると関数\\[-y=f(x)~すなわち~y=-f(x)\\]のグラフとなる．</p><p> $y$ 軸に関して対称移動すると関数\\[y=f(-x)\\]のグラフとなる．</p><p>原点に関して対称移動すると関数\\[-y=f(-x)~すなわち~y=-f(-x)\\]のグラフとなる．</p>"});
formula.push({topic: 2.111,  word: "３次の乗法公式", text: "<div><ol><li>$(a+b)^3=a^3+3a^2b+3ab^2+b^3$ </li><li>$(a-b)^3=a^3-3a^2b+3ab^2-b^3$ </li><li>$(a+b)(a^2-ab+b^2)=a^3+b^3$ </li><li>$(a-b)(a^2+ab+b^2)=a^3-b^3$ </li></ol></div>"});
formula.push({topic: 2.112,  word: "二項定理", text: "<div>\\[(a+b)^n=\\kumi{n}0~a^n+\\kumi{n}1~a^{n-1}b+\\kumi{n}2~a^{n-2}b^2+\\cdots+\\kumi{n}n~b^n\\]</div> シグマ記法では以下の通り。\\[(a+b)^n=\\sig{k=0}{n}\\kumi{n}k~a^{n-k}~b^k\\]"});
  formula.push({topic: 2.113,  word: "整式の除法の定義", text: "整式 $A$ を整式 $B$ で割ったときの商が $Q$, 余りが $R$ とは以下が成り立つことである。\\[A=BQ+R\\]ただし, $R$ の次数は $B$ の次数より小さいものとする。"});
  formula.push({topic: 2.114,  word: "分数式の定義", text: "$A$ を整式, $B$ を１次以上の整式としたとき, $\\frac{A}B$ の形で表される式。"});
  formula.push({topic: 2.115,  word: "有理式の定義", text: "整式と分数式の総称。"});
  formula.push({topic: 2.116,  word: "多項定理", text: " $(a+b+c)^n$ の展開式の一般項は\\[\\bun{n!}{p!q!r!}~a^pb^qc^r\\]ただし, $p+q+r=n$ である。"});
  formula.push({topic: 2.117,  word: "虚数単位の定義", text: "２乗すると $-1$ になる数の一方を $i$, 他方を $-i$ と定める。すなわち, 次の式が成立する。\\[i^2=-1\\]$i$ を虚数単位とよぶ。"});
  formula.push({topic: 2.118,  word: "複素数の定義", text: "実数 $a,~b$ と虚数単位 $i$ を用いて\\[a+bi\\]の形に表される数。"});
  formula.push({topic: 2.119,  word: "実部・虚部の定義", text: "$a,~b$ は実数とする。複素数 $a+bi$ において, $a$ を実部, $b$ を虚部という。"});
  formula.push({topic: 2.120,  word: "虚数の定義", text: "実数でない複素数のこと。"});
  formula.push({topic: 2.121,  word: "純虚数の定義", text: "実部が $0$ である虚数のこと。"});
  formula.push({topic: 2.122,  word: "複素数の相等の定義", text: "２つの複素数が等しいとは, それらの実部どうし, 虚部どうしがそれぞれ等しいことである。したがって, $a,~b,~c,~d$ を実数として以下が成り立つ。\\[a+bi=c+di\\iff a=c~かつ~b=d\\]\\[a+bi=0\\iff a=0~かつ~b=0\\]"});
  formula.push({topic: 2.123,  word: "共役な複素数の定義", text: "$a,~b$ は実数とする。複素数 $\\al =a+bi$ に対して, それに共役な複素数を $\\overline{\\al}$ で表し, 以下のように定める。\\[\\overline{\\al}=a-bi\\]"});
  formula.push({topic: 2.124,  word: "負の数の平方根の計算", text: "$a>0$ のとき, $\\rt{-a}=\\rt{a}~i$"});
  formula.push({topic: 2.125,  word: "２次方程式の解の公式", text: "２次方程式 $ax^2+bx+c=0$ の解は\\[x=\\bun{-b\\pm\\rt{b^2-4ac}}{2a}\\]また, $ax^2+2bx+c=0$ の解は\\[x=\\bun{-b\\pm\\rt{b^2-ac}}{a}\\] "});
  formula.push({topic: 2.126,  word: "２次方程式の解の判別", text: "２次方程式 $ax^2+bx+c=0$ の解について以下が成り立つ。<ol><li>$D>0 \\iff $異なる２つの実数解をもつ </li><li>$D=0 \\iff $重解をもつ </li><li>$D<0 \\iff$ 異なる２つの虚数解をもつ</li></ol>ただし, $D=b^2-4ac$ である。"});
  formula.push({topic: 2.127,  word: "２次方程式の解と係数の関係", text: "２次方程式 $ax^2+bx+c=0$ の２つの解を $\\al,~\\beta$ とすると\\[\\al+\\beta=-\\bun{b}a,~~\\al\\beta=\\bun{c}a\\]"});
  formula.push({topic: 2.128,  word: "２次式の因数分解", text: "２次方程式 $ax^2+bx+c=0$ の２つの解を $\\al,~\\beta$ とすると\\[ax^2+bx+c=a(x-\\al)(x-\\beta)\\]"});
  formula.push({topic: 2.129,  word: "２次方程式の実数解の符号", text: "２次方程式 $ax^2+bx+c=0$ の判別式を$D$, ２つの解を $\\al,~\\beta$ とすると次が成り立つ。<ol><li>$\\al,~\\beta$ がともに正$\\iff D\\geqq0,~\\al+\\beta>0,~\\al\\beta>0$ </li><li>$\\al,~\\beta$ がともに負$\\iff D\\geqq0,~\\al+\\beta<0,~\\al\\beta>0$ </li><li>$\\al,~\\beta$ が異符号$\\iff \\al\\beta<0$</li></ol>"});
  formula.push({topic: 2.130,  word: "剰余の定理", text: "整式 $P(x)$ を $x-\\al$ で割った余りは $P(\\al)$ である。"});
  formula.push({topic: 2.131,  word: "因数定理", text: "整式 $P(x)$ が $x-\\al$ を因数にもつ $\\iff P(\\al)=0$"});
  formula.push({topic: 2.132,  word: "$n$ 次方程式の定義", text: "$P(x)$ を $n$ 次の整式とするとき, 方程式 $P(x)=0$ を $n$ 次方程式という。"});
  formula.push({topic: 2.1325,  word: "代数学の基本定理", text: "一般に, $n$ 次方程式は $n$ 個の複素数解をもつ。"});
  formula.push({topic: 2.133,  word: "恒等式の定義", text: "式の中の文字にどんな数値を代入しても成り立つ等式。"});
  formula.push({topic: 2.134,  word: "恒等式となる条件", text: "$P(x),~Q(x)$ は整式とする。$P(x)=Q(x)$ が恒等式であるための必要十分条件は, $P(x),~Q(x)$ の同じ次数の項の係数が一致することである。例えば\\[ax^2+bx+c=a'x^2+b'x+c'\\]が $x$ についての恒等式である\\[\\iff a=a',~b=b',~c=c'\\]"});
  formula.push({topic: 2.135,  word: "比例式の定義", text: "$\\frac{x}{y}=\\frac{z}{w}$ のように, 比の値が等しいことを表す式。"});
  formula.push({topic: 2.144,  word: "連比の定義", text: "$x:y:z$ を $x,~y,~z$ の連比という。"});
  formula.push({topic: 2.146,  word: "実数の自乗の性質", text: "実数 $a$ に対して\\[a^2\\geqq0\\]特に\\[a^2=0\\iff a=0\\]"});
  formula.push({topic: 2.147,  word: "相加・相乗平均の不等式", text: "$a>0,~b>0$ のとき\\[\\bun{a+b}2\\geqq \\rt{ab}\\]等号が成り立つのは $a=b$ のときである。"});
  formula.push({topic: 2.148,  word: "０以上の数の大小と２乗", text: "$a\\geqq0,~b\\geqq0$ のとき\\[a\\geqq b\\iff a^2\\geqq b^2\\]"});
  formula.push({topic: 2.149,  word: "３次方程式の解と係数の関係", text: "３次方程式\\[ax^3+bx^2+cx+d=0\\] の３つの解を $\\al,~\\beta,\\gamma$ とすると\\[\\al+\\beta+\\gamma=-\\bun{b}a,\\]\\[\\al\\beta+\\beta\\gamma+\\gamma\\al=\\bun{c}a,\\]\\[\\al\\beta\\gamma=-\\bun{d}a\\]"});
  formula.push({topic: 2.21,  word: "２点間の距離公式", text: "２点 $(x_1,~y_1),~(x_2,~y_2)$ 間の距離は\\[\\rt{(x_2-x_1)^2+(y_2-y_1)^2}\\]"});
  formula.push({topic: 2.211,  word: "内分点の定義", text: "$m>0,~n>0$ とする。点 P が線分 AB を $m:n$ に内分するとは, 線分 AB 上に点 P があり\\[\\mr{AP}:\\mr{BP}=m:n\\]であること。"});
  formula.push({topic: 2.212,  word: "数直線上の内分点公式", text: "数直線上で $\\mr{A}(a),~\\mr{B}(b)$ とする。点 $\\mr{P}(x)$ が線分 AB を $m:n$ に内分するとき, \\[x=\\bun{na+mb}{m+n}\\]"});
  formula.push({topic: 2.213,  word: "外分点の定義", text: "$m>0,~n>0,~m\\ne n$ とする。点 P が線分 AB を $m:n$ に外分するとは, 線分 AB の延長上に点 P があり\\[\\mr{AP}:\\mr{BP}=m:n\\]であること。"});
  formula.push({topic: 2.214,  word: "数直線上の外分点公式", text: "数直線上で $\\mr{A}(a),~\\mr{B}(b)$ とする。点 $\\mr{P}(x)$ が線分 AB を $m:n$ に外分するとき, \\[x=\\bun{-na+mb}{m-n}\\]"});
  formula.push({topic: 2.215,  word: "内分点・外分点公式", text: "２点 $\\mr{A}(x_1,~y_1),~\\mr{B}(x_2,~y_2)$ を $m:n$ に内分する点の座標は\\[\\left(\\bun{nx_1+mx_2}{m+n},~\\bun{ny_1+my_2}{m+n}\\right)\\]$m:n$ に外分する点の座標は\\[\\left(\\bun{-nx_1+mx_2}{m-n},~\\bun{-ny_1+my_2}{m-n}\\right)\\] 特に, 線分 AB の中点は\\[\\left(\\bun{x_1+x_2}2,~\\bun{y_1+y_2}2\\right)\\]"});
  formula.push({topic: 2.216,  word: "中線の定義", text: "三角形の頂点とその対辺の中点を結ぶ線分を中線という。"});
  formula.push({topic: 2.217,  word: "三角形の重心の定義", text: "三角形において,３本の中線が交わる点のこと。重心はそれぞれの中線を $2:1$ に内分する。"});
  formula.push({topic: 2.218,  word: "三角形の座標の公式", text: "$\\mr{A}(x_1,~y_1),~\\mr{B}(x_2,~y_2),~\\mr{C}(x_3,~y_3)$ を頂点とする $\\tri{ABC}$ の重心の座標は\\[\\left(\\bun{x_1+x_2+x_3}3,~\\bun{y_1+y_2+y_3}3\\right)\\]"});
  formula.push({topic: 2.219,  word: "方程式の表す図形の定義", text: "一般に, $x,~y$ についての方程式をみたす点$(x,~y)$ すべての集合を, その方程式の表す図形という。"});
  formula.push({topic: 2.220,  word: "図形の方程式の定義", text: "その図形上にある点だけが満たす方程式のこと。"});
  formula.push({topic: 2.221,  word: "直線の傾きの定義", text: "２点 $(x_1,~y_1),~(x_2,~y_2)$ を通る直線の傾きは\\[\\bun{y_2-y_1}{x_2-x_1}\\]ただし, $x_1=x_2$ のときは定義されない。"});
  formula.push({topic: 2.222,  word: "１点と傾きによる直線の立式", text: "点 $(a,~b)$ を通り, 傾き $m$ の直線の方程式は\\[y-b=m(x-a)\\]"});
  formula.push({topic: 2.223,  word: "通る２点による直線の立式", text: "２点 $(x_1,~y_1),~(x_2,~y_2)$ を通る直線 $l$ の方程式は, $x_1\\ne x_2$ のとき\\[l:y-y_1=m(x-x_1)\\]ただし, 傾き $m=\\frac{y_2-y_1}{x_2-x_1}$ である。$x_1=x_2$ のときには\\[l:x=x_1\\]"});
  formula.push({topic: 2.224,  word: "切片の定義", text: "直線と $x$ 軸との交点の $x$ 座標をその直線の $x$ 切片という。直線と $y$ 軸との交点の $y$ 座標をその直線の $y$ 切片という。"});
  formula.push({topic: 2.225,  word: "２直線の平行・垂直条件", text: "傾きがそれぞれ $m,~n$ である２直線について<ol><li>平行となるのは $m=n$ のとき </li><li>垂直となるのは $mn=−1$ のとき</li></ol>また, ２直線\\[a_1x+b_1y+c_1=0,\\]\\[a_2x+b_2x+c_2=0\\]について<ol><li>平行となるのは $a_1b_2-a_2b_1=0$ のとき </li><li>垂直となるのは $a_1a_2+b_1b_2=0$ のとき</li></ol>"});
  formula.push({topic: 2.226,  word: "点と直線の距離公式", text: "点 $(x_0,~y_0)$ と直線 $ax+by+c=0$ の距離 $d$ は\\[d=\\bun{|ax_0+by_o+c|}{\\rt{a^2+b^2}}\\]", canvasScript:'start=[-1.5,-1.5]; end=[1.5,1.5];pointO=[0, 0]; drawEnko({ center:[0,0], radius:1 });pointA=polar({radius:1,degree:330});pointB=polar({radius:1,degree:240});function ff(x){var katamuki = (pointB[1]-pointA[1])/(pointB[0]-pointA[0]);return katamuki * (x-pointA[0])+pointA[1];}drawGraph({func:ff});pointM=bunten({between:[pointA, pointB],rate:[1,1]});pointMark({points:[[pointA],[pointB],[pointM],[pointO]]});drawLine({between:[pointO,pointM],color:"red",width:2});verticalMark({at:pointM,to:pointB,size:2,clock:true});drawHenko({from:pointO,to:pointM,clock:true,string:"d",color:"red"}); '});
  formula.push({topic: 2.227,  word: "円の方程式①", text: "点 $(a,~b)$ を中心とする半径 $r$ の円の方程式は\\[(x-a)^2+(y-b)^2=r^2\\]特に, 原点中心とする半径 $r$ の円の方程式は\\[x^2+y^2=r^2\\]"});
  formula.push({topic: 2.228,  word: "円の方程式②", text: "一般に, 円の方程式は次の形でも表される。\\[x^2+y^2+lx+my+n=0\\]"});
  formula.push({topic: 2.229,  word: "円と直線の位置関係①", text: "円と直線の式を連立させて得られた方程式が次であるとする。\\[ax^2+bx+c=0\\]このとき $D=b^2-4ac$ とすると, 円と直線の位置関係は次。<ol><li>$D>0$ のとき, ２交点で交わる </li><li>$D=0$ のとき, 接する</li><li>$D<0$ のとき, 共有点をもたない</li></ol>"});
  formula.push({topic: 2.230,  word: "円と直線の位置関係②", text: "半径 $r$ の円と直線について, 円の中心と直線の距離を $d$ とするとき, 円と直線の位置関係は次。<ol><li>$d< r$ のとき, ２交点で交わる </li><li>$d=r$ のとき, 接する</li><li>$d>r$ のとき, 共有点をもたない</li></ol>"});
  formula.push({topic: 2.231,  word: "円の接線公式", text: "円 $x^2+y^2=r^2$ 上の点 $(x_0,~y_0)$ における接線の方程式は\\[x_0x+y_0y=r^2\\]"});
  formula.push({topic: 2.232,  word: "軌跡の定義", text: "与えられた条件を満たす点全体の集合を, その条件を満たす点の軌跡という。"});
  formula.push({topic: 2.233,  word: "アポロニウスの円の定義", text: "２定点 A, B に対し\\[\\mr{AP}:\\mr{BP}=m:n\\] を満たす点 P の軌跡は, 線分 AB を $m:n$ に内分する点, 外分する点を直径の両端とする円である。この円をアポロニウスの円という。ただし, $m>0,~n>0,~m\\ne n$ である。"});
  formula.push({topic: 2.234,  word: "不等式の表す領域の定義", text: "$x,~y$ についての不等式に対して, それを満たす点 $(x,~y)$ 全体の集合を, その不等式の表す領域という。"});
  formula.push({topic: 2.235,  word: "不等式の表す領域の図示", text: "$y=f(x)$ の表す図形を $E$ とすると, 不等式の表す領域は次。<ol><li>$y>f(x)\\cdots E$ の上側 </li><li>$y< f(x)\\cdots E$ の下側 </li></ol>"});
  formula.push({topic: 2.236,  word: "円の内部・外部を表す不等式", text: "$円~C:(x-a)^2+(y-b)^2=r^2$ に対して, 不等式の表す領域は次。\\[(x-a)^2+(y-b)^2< r^2\\]\\[\\cdots ~C~ の内部\\]\\[(x-a)^2+(y-b)^2> r^2\\]\\[\\cdots ~C~ の外部\\]"});
  formula.push({topic: 2.301,  word: "動径の定義", text: "平面上で一点を中心として半直線を回転させるとき, その半直線のこと。"});
  formula.push({topic: 2.302,  word: "始線の定義", text: "動径の始めの位置を示す半直線のこと。"});
  formula.push({topic: 2.303,  word: "回転角の正負の定義", text: "時計の針の回転と同じ向き (右回り) を負の向き, その逆の向き (左回り) を正の向きとする。また, それぞれの回転角を負の角, 正の角という。 "});
  formula.push({topic: 2.304,  word: "一般角の定義", text: "$0^\\circ$以上 $360^\\circ$ 度以下に限らず, 実数により表された角。"});
  formula.push({topic: 2.305,  word: "動径の表す一般角の計算", text: "動径の表す角の１つが $\\al$ のとき, その一般角 $\\sita$ は次のように表せる。\\[\\sita=\\al+360^\\circ\\times n\\]ただし, $n$ は任意の整数である。"});
  formula.push({topic: 2.306,  word: "弧度法の定義", text: "半径が１の円において, 弧長が１となるような中心角の大きさを１ラジアンとする。１ラジアンを単位とする角の表し方を弧度法という。\\[1~ラジアン=\\bun{180^\\circ}\\pi,\\]\\[\\pi~ラジアン=180^\\circ\\]"});
  formula.push({topic: 2.307,  word: "弧度法による一般角の計算", text: "動径の表す角の１つが $\\al$ のとき, その一般角 $\\sita$ は次のように表せる。\\[\\sita=\\al+2n\\pi\\]ただし, $n$ は任意の整数である。"});
  formula.push({topic: 2.308,  word: "扇形の弧長と面積の公式", text: "半径 $r$ ,中心角 $\\sita$ の扇形の弧の長さを $l$ , 面積を $S$ とすると\\[l=r\\sita~,\\]\\[S=\\bun12r^2\\sita=\\bun12lr\\]"});
  formula.push({topic: 2.309,  word: "単位円の定義", text: "原点を中心とする半径１の円。"});
  formula.push({topic: 2.310,  word: "三角関数の定義", text: "単位円上の点 $\\mr{P}$ を考える。$x$ 軸の正の向きを始線として, 動径 $\\mr{OP}$ の表す角が $\\sita$ のとき\\[\\cos\\sita=\\mr{P}~の~x~座標~,\\]\\[\\sin\\sita=\\mr{P}~の~y~座標~,\\] \\[\\tan\\sita=\\mr{OP}~の~傾き\\]と定める。ただし $n$ を整数として$\\sita=\\frac\\pi2+n\\pi$ のとき, $\\tan \\sita$ は定義されない。 "});
  formula.push({topic: 2.311,  word: "三角関数の値域", text: "角 $\\sita$ がすべての値をとり得るとき, 三角関数のとり得る値の範囲は次。\\[-1\\leqq\\cos\\sita\\leqq1~,\\]\\[-1\\leqq\\sin\\sita\\leqq1~,\\]$\\tan\\sita$ は全ての実数値をとる。"});
  formula.push({topic: 2.312,  word: "三角関数の相互関係", text: "\\[\\sin^2+\\cos^2\\sita=1~,\\]\\[\\tan\\sita=\\bun{\\sin\\sita}{\\cos\\sita}~,\\]\\[1+\\tan^2\\sita=\\bun1{\\cos^2\\sita}\\]"});
  formula.push({topic: 2.313,  word: "$\\sita+2n\\pi$ の三角関数", text: "$n$ は整数とする。<ol><li>$\\sin(\\sita+2n\\pi)=\\sin\\sita$</li><li>$\\cos(\\sita+2n\\pi)=\\cos\\sita$ </li><li>$\\tan(\\sita+2n\\pi)=\\tan\\sita$ </li></ol>"});
  formula.push({topic: 2.314,  word: "$-\\sita$ の三角関数", text: "<ol><li>$\\sin(-\\sita)=-\\sin\\sita$</li><li>$\\cos(-\\sita)=\\cos\\sita$ </li><li>$\\tan(-\\sita)=-\\tan\\sita$ </li></ol>"});
  formula.push({topic: 2.315,  word: "$\\sita+\\frac\\pi2$ の三角関数", text: "<ol><li>$\\sin(\\sita+\\frac\\pi2)=\\cos \\sita$</li><li>$\\cos(\\sita+\\frac\\pi2)=-\\sin\\sita$ </li><li>$\\tan(\\sita+\\frac\\pi2)=-\\frac1{\\tan\\sita}$</li></ol>"});
  formula.push({topic: 2.316,  word: "$\\sita+\\pi$ の三角関数", text: "<ol><li>$\\sin(\\sita+\\pi)=-\\sin\\sita$</li><li>$\\cos(\\sita+\\pi)=-\\cos\\sita$ </li><li>$\\tan(\\sita+\\pi)=\\tan\\sita$</li></ol>"});
  formula.push({topic: 2.317,  word: "周期の定義", text: "関数 $f(x)$ と定数 $p\\ne0$ を考える。<p>$(*)$: 任意の $x$ に対し $f(x+p)=f(x)$ </p>が成り立つとき, $f(x)$ を周期関数という。また通常, $(*)$ を満たす正の値 $p$ のうち最小のものを $f(x)$ の周期という。 "});
  formula.push({topic: 2.318,  word: "三角関数の周期", text: "$\\sin \\sita$ の周期は $2\\pi$,<br>$\\cos \\sita$ の周期は $2\\pi$,<br>$\\tan \\sita$ の周期は $\\pi$ である。 "});
  formula.push({topic: 2.319,  word: "偶関数・気関数の定義", text: "$f(x)$ が次の条件を満たすとき, 以下のように呼ぶ。<p>$f(-x)=f(x)~\\cdots~ f(x)$ は偶関数</p><p>$f(-x)=-f(x)~\\cdots~ f(x)$ は奇関数</p>"});
  formula.push({topic: 2.320,  word: "加法定理", text: "以下は複号同順とする。<div>\\[\\sin(\\al\\pm\\beta)=\\sin\\al\\cos\\beta\\mp\\cos\\al\\sin\\beta~,\\]\\[\\cos(\\al\\pm\\beta)=\\cos\\al\\cos\\beta\\pm\\sin\\al\\sin\\beta~,\\]\\[\\tan(\\al\\pm\\beta)=\\bun{\\tan\\al\\pm\\tan\\beta}{1\\mp\\tan\\al\\tan\\beta}\\]</div>"});
  formula.push({topic: 2.321,  word: "２直線のなす角の公式", text: "互いに垂直でない２直線の傾きがそれぞれ $m,~n$ であるとする。２直線のなす角 $\\sita~(0\\leqq\\sita<\\frac\\pi2)$ について\\[\\tan\\sita=\\left|\\bun{m-n}{1+mn}\\right|\\]が成リ立つ。"});
  formula.push({topic: 2.322,  word: "２倍角の公式", text: "\\begin{align}\\sin2\\sita&=2\\sin\\sita\\cos\\sita\\\\[2mm]\\cos2\\sita&=\\cos^2\\sita-\\sin^2\\sita\\\\[1mm]&=1-2\\sin^2\\sita\\\\[1mm]&=2\\cos^2\\sita-1\\\\[2mm]\\tan2\\sita&=\\bun{\\tan\\sita}{1-\\tan^2\\sita}\\end{align}"});
  formula.push({topic: 2.323,  word: "半角の公式", text: "\\begin{align}\\sin^2\\bun\\sita2=\\bun{1-\\cos\\sita}2\\\\[2mm]\\cos^2\\bun\\sita2=\\bun{1+\\cos\\sita}2\\end{align}"});
  formula.push({topic: 2.324,  word: "三角関数の合成公式", text: "\\begin{align}&a\\sin\\sita+b\\cos\\sita\\\\[2mm]=&\\rt{a^2+b^2}~\\sin(\\sita+\\al)\\end{align}ただし,\\begin{align}\\cos\\al=\\bun{a}{\\rt{a^2+b^2}}~,\\\\ \\sin\\al=\\bun{b}{\\rt{a^2+b^2}}\\end{align}である。"});
  formula.push({topic: 2.325,  word: "和積の公式", text: "\\begin{align}\\sin A+\\sin B&=2\\sin\\bun{A+B}2\\cos\\bun{A-B}2\\\\[2mm]\\sin A-\\sin B&=2\\cos\\bun{A+B}2\\sin\\bun{A-B}2\\\\[2mm]\\cos A+\\cos B&=2\\cos\\bun{A+B}2\\cos\\bun{A-B}2\\\\[2mm]\\cos A-\\cos B&=-2\\sin\\bun{A+B}2\\sin\\bun{A-B}2\\end{align}"});
  formula.push({topic: 2.401,  word: "０や負の指数の定義", text: "$a\\ne0$ , 実数 $x$ に対して\\[a^0=1~,~a^{-x}=\\bun1{a^x}\\]"});
  formula.push({topic: 2.402,  word: "指数法則 (数学II)", text: "$a>0,~b>0$とする。実数 $x,~y$ に対して<ol><li>$a^x\\times a^y=a^{x+y}$</li><li>$a^x\\div a^y=a^{x-y}$</li><li>$(a^x)^y=a^{xy}$ </li><li>$(ab)^p=a^xb^x$ </li><li>$\\left(\\bun{a}b\\right)^x=\\bun{a^x}{b^x}$ </li></ol>"});
  formula.push({topic: 2.403,  word: "累乗根の定義", text: "$a$ を実数, $n$ を自然数とする。$n$ 乗すると $a$ になる数を 「$a$ の $n$ 乗根」という。つまり, \\[x^n=a\\]の解 $x$ のすべてのこと。各場合について実数 $x$ の個数・表記は次の通り。\\begin{array}{c|c|c}&a\\geqq0&a<0\\\\ \\hline n ~は偶数 &\\sqrt[n]a,~-\\sqrt[n]a&なし \\\\ \\hline n ~は奇数 &\\sqrt[n]a&\\sqrt[n]a\\end{array} ただし, $n$ が偶数, $a\\geqq0$ のときは\\[\\sqrt[n]a\\geqq0,~-\\sqrt[n]a\\leqq0\\]と定める。"});
  formula.push({topic: 2.404,  word: "累乗根の性質", text: " $a>0,~b>0$ で $m,~n$ が正の整数のとき, 次が成り立つ。<ol><li>$\\sqrt[n]{a}~\\sqrt[n]{b}=\\sqrt[n]{ab}$ </li><li>$\\bun{\\sqrt[n]{a}}{\\sqrt[n]{b}}=\\sqrt[n]{\\bun{a}b}$ </li><li>$(\\sqrt[n]a)^m=\\sqrt[n]{a^m}$ </li><li>$\\sqrt[m]{\\sqrt[n]a}=\\sqrt[mn]a$ </li></ol>"});
    formula.push({topic: 2.405,  word: "有理数の指数と累乗の関係", text: "$a>0$ であり, $m$ が整数, $n$ が自然数のとき,\\[a^{\\frac{m}n}=\\sqrt[n]{a^m}\\]特に\\[a^\\frac12=\\rt2,~a^\\frac1n=\\sqrt[n]a\\]である。"});
  formula.push({topic: 2.406,  word: "指数関数の定義・性質", text: "定数 $a$ は $a>0,~a\\ne1$ を満たすとる。このとき\\[y=a^x\\]を $a$ を底とする指数関数という。その性質は次。<ol><li>定義域は実数全体, 値域は正の実数全体である </li><li>$a>1$ のとき増加関数, $0< a<1$ のとき減少関数である</li><li>グラフは点 $(0,~1)$ を通り, $x$ 軸に漸近する</li><li>$x$ 座標が大きくなるほど接線の傾きは大きくなる </li></ol>"});
  formula.push({topic: 2.407,  word: "指数関数と方程式・不等式", text: "$a>1$ とき\\[a^x\\leqq a^y \\iff x\\leqq y\\]$0< a< 1$ のとき\\[a^x\\leqq a^y\\iff x\\geqq y\\]いずれの場合にも\\[a^x= a^y\\iff x= y\\]が成り立つ。 "});
  formula.push({topic: 2.408,  word: "対数の定義", text: "$a>0,~a\\ne1$ とする。$a$ を $x$ 乗すると $b$ になるとき, $x$ を $\\log_a b$ と表す。つまり\\[a^x=b\\iff x=\\log_ab\\]このとき, $\\log_ab$ を「$a$ を底とする $b$ の対数」といい, $b$ をその真数という。定義により $b>0$ である。"});
  formula.push({topic: 2.409,  word: "基本的な対数", text: "\\[\\log_a1=0,~\\log_aa=1\\]"});
  formula.push({topic: 2.410,  word: "対数の計算法則", text: "<ol><li>$\\log_axy=\\log_ax+\\log_ay$ </li><li>$\\log_a\\frac{x}y=\\log_ax-\\log_ay$ </li><li>$\\log_ax^p=p\\log_ax~~(p~は実数)$</li></ol>"});
  formula.push({topic: 2.411,  word: "底の交換法則", text: "\\[\\log_ab=\\bun{\\log_cb}{\\log_ca}\\]"});
  formula.push({topic: 2.412,  word: "対数関数の性質", text: "$y=\\log_ax$ の性質は次。<ol><li>定義域は正の実数全体, 値域は実数全体である </li><li>$a>1$ のとき増加関数, $0< a<1$ のとき減少関数である</li><li>グラフは点 $(1,~0)$ を通り, $y$ 軸に漸近する</li><li>指数関数 $y=a^x$ のグラフを直線 $y=x$ に関して対称移動したグラフをもつ</li></ol>"});
  formula.push({topic: 2.413,  word: "対数関数と方程式・不等式", text: "$x>0,~y>0$ とする。<br>$a>1$ のとき\\[\\log_ax\\leqq\\log_ay\\iff x\\leqq y\\]$0< a<1$ のとき\\[\\log_ax\\leqq\\log_ay\\iff x\\geqq y\\]いずれのときも\\[\\log_ax=\\log_ay\\iff x= y\\]"});
  formula.push({topic: 2.501,  word: "平均変化率の定義", text: "関数 $y=f(x)$ において $x$ の値が $a$ から $b$ まで変化するときの平均変化率を次のように定める。\\[平均変化率=\\bun{f(b)-f(a)}{b-a}\\]"});
  formula.push({topic: 2.502,  word: "極限値の定義(数II)", text: "$x~(\\ne a)$ の値が $a$ に限りなく近づくとき, 関数 $f(x)$ の値が一定の値 $b$ に限りなく近づくことを\\[\\li{x}{a}f(x)=b\\]と書き, $b$ をこのときの極限値という。"});
  formula.push({topic: 2.503,  word: "微分係数の定義", text: " \\[f'(a)=\\li{h}{0}\\bun{f(a+h)-f(a)}{h}\\]つまり, $x$ の値が $a$ から $a+h$ まで変化するときの $f(x)$ の平均変化率に対して, $h$ を限りなく 0 に近づけた際の極限値を微分係数 $f'(a)$ と定める。$f'(a)$ は 曲線 $y=f(x)$ の点 $(a,~f(a))$ における接線の傾きに等しい。"});
  formula.push({topic: 2.504,  word: "導関数の定義", text: "関数 $f(x)$ に対し, $x$ のおのおのの値 $a$ に微分係数 $f'(a)$ を対応させた関数 $f'(x)$ のこと。\\[f'(x)=\\li{h}{0}\\bun{f(x+h)-f(x)}h\\]"});
  formula.push({topic: 2.505,  word: "整式の導関数の公式", text: "$n$ が自然数のとき\\[(x^n)'=nx^{n-1}\\]\\[(定数)'=0\\]"});
  formula.push({topic: 2.506,  word: "導関数の計算規則", text: "関数 $f(x),~g(x)$ について, $s,~t$ を定数とするとき\\[\\{sf(x)+tg(x)\\}'=sf'(x)+tg'(x)\\]つまり, 項ごとに微分してよく, 微分した後に係数を掛ければよい。"});
   formula.push({topic: 2.507,  word: "接線の公式", text: "曲線 $y=f(x)$ 上の点 $(a,~f(a))$ における接線の方程式は\\[y=f'(a)(x-a)+f(a)\\]"});
  formula.push({topic: 2.508,  word: "関数の増減と導関数", text: "$f'(x)>0$ となる区間において, $f(x)$ は増加する。$f'(x)<0$ となる区間において, $f(x)$ は減少する。"}); 
  formula.push({topic: 2.509,  word: "極大値・極小値の定義", text: "<p>関数 $f(x)$ が $x=a$ を境に増加から減少に変わるとき, $f(a)$ を極大値という。同様に, $x=a$ を境に減少から増加に変わるとき, $f(a)$ を極小値という。</p><p>極大値, 極小値を合わせて極値という。$x=a$ において $f(x)$ が極値をとるとする。このとき, 微分係数 $f'(a)$ が存在するならば $f'(a)=0$ である。</p>"});
  formula.push({topic: 2.601,  word: "原始関数・不定積分の定義", text: "$F'(x)=f(x)$ が成り立つとき, $F(x)$ を「$f(x)$ の原始関数」という。このとき, 任意の定数 $C$ に対して $F(x)+C$ も $f(x)$ の原始関数である。これらをまとめて $\\sekib{}{} ~f(x)~dx$ と表し, 「 $f(x)$ の不定積分」という。つまり,\\[\\sekib{}{} ~f(x)~dx=F(x)+C\\]$C$ を積分定数という。"});
  formula.push({topic: 2.602,  word: "$x^n$ の不定積分の公式", text: "整数 $n~(\\geqq 0)$ に対して\\[\\sekib{}{}~x^n~dx=\\bun1{n+1}x^{n+1}+C\\]$C$ は積分定数である。"});
  formula.push({topic: 2.603,  word: "不定積分の計算規則", text: "定数 $s,~t$ に対して\\begin{align}&~\\sekib{}{}~\\{sf(x)+tg(x)\\}dx\\\\=&~s\\sekib{}{}f(x)dx+t\\sekib{}{}g(x)dx\\end{align}"});
  formula.push({topic: 2.604,  word: "定積分の定義", text: "「$f(x)$ の $a$ から $b$ までの定積分」を $\\sekib{a}{b}f(x)~dx$ と表し, 以下で定める。\\[\\sekib{a}bf(x)dx=F(b)-F(a)\\]ここで, $F(x)$ を $f(x)$ の原始関数としてあり, 右辺は次のようにも書く。\\[\\bigg[F(x)\\bigg]^b_a\\]"});
  formula.push({topic: 2.605,  word: "定積分の計算規則", text: "$s,~t$ を定数とする。\\begin{align}&~\\sekib{a}{b}\\{sf(x)+tg(x)\\}dx\\\\=&~s\\sekib{a}{b}f(x)dx+t\\sekib{a}bg(x)dx\\end{align}"});
  formula.push({topic: 2.606,  word: "定積分の性質", text: "<div><ol><li>$\\sekib{a}{a}f(x)dx=0$ </li><li>$\\sekib{b}{a}f(x)dx=-\\sekib{a}{b}f(x)dx$ </li><li>$\\sekib{a}{b}f(x)dx+\\sekib{b}{c}f(x)dx=\\sekib{a}{c}f(x)dx$</li></ol></div> "});
  formula.push({topic: 2.607,  word: "定積分の微分公式", text: "$a$ を定数のとき, 以下が成り立つ。\\[\\bun{d}{dx}\\sekib{a}{x}f(t)dt=f(x)\\]"});
  
  //ここから数 Ⅲ
 formula.push({topic: 3.101,  word: "放物線の定義・標準形", text: "平面上で定点 $\\mr{F}$ と, $\\mr{F}$ を通らない定直線 $l$ から等距離にある点の軌跡を放物線という。また, $\\mr{F}$ を焦点, $l$ を準線という。特に, $xy$ 平面上で\\[\\mr{F}~(p,~0),~l:x=-p\\] のとき, 放物線の式は\\[y^2=4px\\] となる。\\[\\mr{F}~(0,~p),~l:y=-p\\] のとき, 放物線の式は\\[x^2=4py\\] となる。これらを放物線の式の標準形という。"});
 formula.push({topic: 3.102,  word: "楕円の定義・標準形", text: " 平面上で２焦点 $\\mr{F},~\\mr{F'}$ からの距離の和が一定である点 $\\mr{P}$ の軌跡を楕円という。特に, $a>c>0$ に対し\\[\\mr{F}(c,~0),~\\mr{F'}(-c,~0),\\]\\[\\mr{PF}+\\mr{PF'}=2a\\]のとき, 楕円の式は次である。<div>\\[\\bun{x^2}{a^2}+\\bun{y^2}{b^2}=1~~(b^2=a^2-c^2)\\]</div>同様に, \\[\\mr{F}(0,~c),~\\mr{F'}(0,~-c),\\]\\[\\mr{PF}+\\mr{PF'}=2a\\]のときは<div>\\[\\bun{x^2}{b^2}+\\bun{y^2}{a^2}=1~~(b^2=a^2-c^2)\\]</div>これらの式を楕円の式の標準形という。"});  
  formula.push({topic: 3.103,  word: "楕円の図示", text: "$a>0,~b>0$ とする。\\[\\bun{x^2}{a^2}+\\bun{y^2}{b^2}=1\\]の表す図形は, 単位円\\[x^2+y^2=1\\]を $x$ 軸方向に $a$ 倍, $y$ 軸方向に $b$ 倍した楕円である。このとき, 座標軸との交点$(\\pm a,~0),~(0,~\\pm b)$ を楕円の頂点といい, 原点 $\\mr{O}$ を楕円の中心という。"});
  formula.push({topic: 3.104,  word: "双曲線の定義・標準形", text: "平面上で２焦点 $\\mr{F},~\\mr{F'}$ からの距離の差が一定である点 $\\mr{P}$ の軌跡を双曲線という。特に, $c>a>0$ に対し\\[\\mr{F}(c,~0),~\\mr{F'}(-c,~0),\\]\\[|\\mr{PF}-\\mr{PF'}|=2a\\]のとき, 双曲線の式は次である。\\[\\bun{x^2}{a^2}-\\bun{y^2}{b^2}=1~~(b^2=c^2-a^2)\\]同様に\\[\\mr{F}(0,~c),~\\mr{F'}(0,~-c),\\]\\[|\\mr{PF}-\\mr{PF'}|=2a\\]のときには\\[\\bun{x^2}{b^2}-\\bun{y^2}{a^2}=-1~~(b^2=c^2-a^2)\\]これらの式を双曲線の式の標準形という。"});
  formula.push({topic: 3.105,  word: "双曲線の図示", text: "$a>0,~b>0$ とする。\\[\\bun{x^2}{a^2}-\\bun{y^2}{b^2}=1\\]の表す双曲線は, 曲線 \\[y=\\pm\\rt{x^2-1}\\]を $x$ 軸方向に $a$ 倍, $y$ 軸方向に $b$ 倍したものであり, 直線 $y=\\pm\\frac{b}ax$ に漸近する。このとき, $x$ 軸との交点 $(\\pm a,~0)$ を双曲線の頂点といい, 原点 $\\mr{O}$ を双曲線の中心という。 同様に\\[\\bun{x^2}{a^2}-\\bun{y^2}{b^2}=-1\\]の表す双曲線は, 曲線 \\[y=\\pm\\rt{x^2+1}\\]を $x$ 軸方向に $a$ 倍, $y$ 軸方向に $b$ 倍したものであり, 直線 $y=\\pm\\frac{b}ax$ に漸近する。"});
  formula.push({topic: 3.106,  word: "曲線の平行移動の公式", text: "曲線 $f(x,~y)=0$ を $x$ 軸方向に $a$, $y$ 軸方向に $b$ だけ平行移動して得られる曲線の方程式は\\[f(x-a,~y-b)=0\\] "});
  formula.push({topic: 3.107,  word: "離心率の定義", text: "２次曲線は, 平面上で焦点 F からの距離 PF と準線 $l$ からの距離 PH の比 $e=\\frac{\\mr{PF}}{\\mr{PH}}~(>0)$ が一定である点 P の軌跡 $C$ である。$e$ の値に応じ, $C$ の種類は次の通り。<ol><li> $0< e<1$ のとき 楕円 </li><li>$e=1$ のとき 放物線 </li><li>$e>1$ のとき 双曲線 </li></ol>"});
  //ここから数学A
  formula.push({topic: 4.101, word: "集合の要素の個数", text: "要素の個数が有限である集合を有限集合といい, 要素の個数が有限でない集合を無限集合という。有限集合 $A$ の要素の個数 $n(A)$ と表す。"});
	formula.push({topic: 4.102, word: "和集合の要素の個数", text: "<div>\\[n(A\\cup B)=n(A)+n(B)-n(A\\cap B)\\]</div>特に, $A\\cap B =\\phi$ のとき \\[n(A\\cup 	B)=n(A)+n(B)\\]"});
formula.push({topic: 4.103, word: "補集合の要素の個数", text: "全体集合 $U$ に対し, その部分集合 $A$ の補集合 $\\overline{A}$ の要素の個数は\\[n(\\overline{A})=n(U)-n(A)\\]"});
formula.push({topic: 4.104, word: "和の法則", text: "2つの事柄 $A,~B$ は同時には起こらないとする。$A$ の起こり方が $m$ 通り, $B$ の起こり方が $n$ 通りあるとき, $A$ または $B$ の起こる場合の数は\\[m+n ~通り\\]"});
formula.push({topic: 4.105 , word: "積の法則", text: "事柄 $A$ の起こり方が $m$ 通りあり, その各々について, 事柄 $B$ の起こり方が $n$　通りあるとき, $A,~B$ がともに起こる場合の数は\\[m\\times n ~通り\\]"});
formula.push({topic: 4.1055, word: "階乗", text: "$1$ から $n$ までの整数の積を 「 $n$ の階乗」といい, $n!$ と表す。つまり, \\[n!=n(n-1)(n-2)\\cdots~\\cdot2\\cdot1\\]"});
formula.push({topic: 4.106, word: "順列", text: "並ぶ順序によって区別される並びのことを順列という。$n$ 個の異なるものから $r$ 個を選んで並べるとき, できる順列の数は\\begin{align*}\\jun{n}{r}&=n(n-1)(n-2)\\cdots~\\cdot(n-r+1)\\\\&=\\bun{n!}{(n-r)!}\\end{align*}"});
formula.push({topic: 4.108, word: "円順列", text: "円形に並んだ順列を円順列という。回転により一致する円順列どうしは同じものと見なされる。$n$ 個の異なるものを並べてできる円順列の数は\\[(n-1)!~通り\\]"});
formula.push({topic: 4.109, word: "重複順列", text: "$n$ 個の異なるものから,くり返し用いることを許して $r$ 個を選び並べる場合の数は\\[n^r~通り\\]"});
formula.push({topic: 4.110, word: "組合わせ", text: "$n$ 個の異なるものから, $r$ 個を選んだ組合せの数は\\begin{align*}\\kumi{n}{r}&=\\bun{n(n-1)(n-2)\\cdots(n-r+1)\\cdot1}{r(r-1)\\cdots \\cdot2\\cdot1}\\\\&=\\bun{n!}{r!(n-r)!}\\end{align*}"});
formula.push({topic: 4.111, word: "同じものを含む順列", text: "$n$ 個のものを１列に並べるとき, 同種のものがそれぞれ $p$ 個, $q$ 個, $r$ 個, $\\cdots$ あるとすると, 並べ方は\\[\\bun{n!}{p!~q!~r!\\cdots}~通り\\]"});
formula.push({topic: 4.112, word: "試行・事象", text: "同じ条件下でくり返し行うことができ, 結果が偶然によって決まる実験や観測のことを試行という。また, それによって起こる結果を事象という。起こり得るすべての事象を合わせて, その試行の全事象という。"});
  //ここから数学 B 
  formula.push({topic: 5.101,  word: "数列の定義", text: "数を一列に並べたもの。一般的には\\[a_1,~a_2,~a_3,~\\cdots,~a_n,~\\cdots\\] のように書き, $\\{a_n\\}$ と略記される。"});
  formula.push({topic: 5.102,  word: "一般項の定義", text: "数列 $\\{a_n\\}$ の第 $n$ 項 $a_n$ を $n$ で表したもの。"});
  formula.push({topic: 5.103,  word: "有限数列の定義", text: "項の個数が有限である数列。"});
  formula.push({topic: 5.104,  word: "無限数列の定義", text: "項の個数が無限である数列。"});
  formula.push({topic: 5.105,  word: "項数の定義", text: "有限数列において, 項の個数を項数という。"});
  formula.push({topic: 5.106,  word: "末項の定義", text: "有限数列において, 最後の項を末項という。"});
  formula.push({topic: 5.107,  word: "等差数列の定義", text: "初項 $a$ に, 次々と一定の数 $d$ を加えていって得られる数列。 また, $d$ をこの数列の公差という。"});
  formula.push({topic: 5.108,  word: "等差数列の一般項の公式", text: "初項 $a$, 公差 $d$ の等差数列 $\\{a_n\\}$ の一般項は\\[a_n=a+(n-1)d\\]"});
  formula.push({topic: 5.109,  word: "等差数列の和公式", text: "初項 $a$, 末項 $l$, 項数 $n$ の等差数列 の和を $S_n$ とすると\\[S_n=\\bun{a+l}2\\times n\\]"});
  formula.push({topic: 5.110,  word: "等比数列の定義", text: "初項 $a$ に, 次々と一定の数 $r$ を掛けていって得られる数列。 また, $r$ をこの数列の公比という。"});
  formula.push({topic: 5.111,  word: "等比数列の一般項の公式", text: "初項 $a$, 公差 $r$ の等差数列 $\\{a_n\\}$ の一般項は\\[a_n=ar^{n-1}\\]"});
  formula.push({topic: 5.112,  word: "等比数列の和公式", text: "初項 $a$, 公差 $r$ の等比数列の初項から第 $n$ 項までの和 $S_n$ は\\begin{equation}S_n=\\begin{cases}\\bun{a(1-r^n)}{1-r}&(r\\ne1)\\\\[2mm]na&(r=1)\\end{cases}\\end{equation}"});
  formula.push({topic: 5.113,  word: "シグマの記法", text: "数列 $\\{a_k\\}$ に対し, $k$ に１から $n$ までのすべての値を代入してとった和を $\\sig{k=1}{n}a_k$ と略記する。つまり,\\[\\sig{k=1}{n}a_k=a_1+a_2+a_3+\\cdots+a_n\\]"});
  formula.push({topic: 5.114,  word: "シグマの公式", text: "\\begin{align}\\sig{k=1}nc&=nc~~~(c~は定数)\\\\\\sig{k=1}nk&=\\bun12n(n+1)\\\\\\sig{k=1}nk^2&=\\bun16n(n+1)(2n+1)\\\\\\sig{k=1}nk^3&=\\bun14n^2(n+1)^2\\end{align}"});
  formula.push({topic: 5.115,  word: "階差数列の定義", text: "数列 $\\{a_n\\}$ に対して\\[b_n=a_{n+1}-a_n\\]として得られる数列 $\\{b_n\\}$ を $\\{a_n\\}$ の階差数列という。 "});
  formula.push({topic: 5.116,  word: "階差数列を用いた一般項の公式", text: "数列 $\\{a_n\\}$ の階差数列が $\\{b_n\\}$ であるとき,\\[a_n=a_1+\\sig{k=1}{n-1}~b_k\\]ただし, $n\\geqq2$である。 "});
  formula.push({topic: 5.117,  word: "数列の和と一般項の関係", text: "数列 $\\{a_n\\}$ の初項から 第 $n$ 項までの和を $S_n$ とすると\\begin{equation}\\begin{cases}a_1=S_1\\\\[2mm]a_n=S_{n}-S_{n-1}~~(n\\geqq2)\\end{cases}\\end{equation}"});
  formula.push({topic: 5.120,  word: "漸化式の定義", text: "数列の項をそれより前の項を用いて定めた規則のことを漸化式という。"});
  formula.push({topic: 5.121,  word: "数学的帰納法の論法", text: "自然数 $n$ に関する命題 $P(n)$ が, すべての自然数 $n$ に対して成り立つことを証明するには, 次の２つを証明すればよい。<ol><li>$P(1)$ が成り立つ</li><li>$P(k)$ が成り立つと仮定すると, $P(k+1)$ が成立する</li></ol>"});
  formula.push({topic: 5.201,  word: "ベクトルの定義", text: "向きと大きさにより定まる量を「ベクトル」という。 例えば, 点 $\\mr{A}$ から点 $\\mr{B}$ までの移動量は, その向きと大きさ(距離)で表せるのでベクトルであり, $\\bect{AB}$ と書く。このとき, $\\mr{A}$ を始点, $\\mr{B}$ を終点といい, 大きさは $|\\bect{AB}|$ で表す。 $\\vec{p}$ のように１文字で表すこともある。"});
  formula.push({topic: 5.202,  word: "ベクトルの相等", text: "$\\beca$ と $\\becb$ の向きと大きさが一致するとき, これらは等しいといい\\[\\beca=\\becb\\] と表す。"});
 formula.push({topic: 5.203,  word: "ベクトルの実数倍・加法", text: "<ol><li>$\\beca$ と同じ向きで大きさが $k$ 倍であるベクトルを $k~\\beca$ と定める。ここで, $-\\beca$ は $\\beca$ と逆向きで大きさが同じベクトルとする。</li><li>$\\beca$ の終点と $\\becb$ の始点をつないで得られるベクトルを $\\beca+\\becb$ と定める。つまり, 次である。\\[\\bect{AB}+\\bect{BC}=\\bect{AC}\\]また, ベクトルの和はつなぐ順序には依らない。つまり, 以下が成立する。\\[\\beca+\\becb=\\becb+\\beca\\]</li><li>$\\beca-\\becb$ を $\\becb+(-\\beca)$ と定める。これより, 任意の始点 O について次である。\\[ \\bect{BA}=\\bect{OA}-\\bect{OB}\\]右辺には以下を用いた。\\begin{align}&~\\bect{OA}-\\bect{OB}\\\\=&~\\bect{OA}+(-\\bect{OB})\\\\=&~\\bect{BO}+\\bect{OA}\\\\=&~\\bect{BA}\\end{align}</li></ol>"});
  formula.push({topic: 5.204,  word: "零ベクトル・単位ベクトルの定義", text: "<ol><li> 大きさが $0$ のベクトルを零ベクトルといい $\\vec0$ で表す。$\\vec0$ は向きをもたないものとする。</li><li>大きさが $1$ のベクトルを単位ベクトルという。$\\beca$ と同じ向きの単位ベクトルは\\[\\vec{e}=\\bun{\\beca}{|\\beca|}\\] </li></ol>"});
  formula.push({topic: 5.205,  word: "ベクトルの計算規則", text: "ベクトルの係数についても, 文字式における扱いと同様である。<ol><li>$kl~\\beca=k(l~\\beca)$ </li><li>$k\\beca+l\\beca=(k+l)\\beca$ </li><li>$k\\beca+k\\becb=k(\\beca+\\becb)$</li></ol>"});
  formula.push({topic: 5.206,  word: "ベクトルの平行条件", text: "$\\beca\\ne\\vec0,~\\becb\\ne\\vec0$ とする。<br>$\\beca /\\!/\\becb$ となるための必要十分条件は$\\becb=k\\beca$ となる実数 $k$ が存在することである。"});
formula.push({topic: 5.207, word: "ベクトルの「一次独立」", text: "$\\beca \\ne \\vec0,~\\becb\\ne\\vec0$ であり $\\beca$ と $\\becb$ が平行でないとき, 「 $\\beca,~\\becb$ は一次独立である」という。このとき, 平面上の任意のベクトル $\\vec{p}$ は\\[\\vec{p}=s\\beca+t\\becb~~~(s,~t ~は実数)\\]の形にそれぞれただ１通りに表される。すなわち\\begin{align}&s\\beca+t\\becb=s'\\beca+t'\\becb\\\\\\iff &s=s',~t=t'\\\\&s\\beca+t\\becb=\\vec0\\\\\\iff &s=t=0\\end{align}である。"});
formula.push({topic: 5.208, word: "直線上の点の扱い", text: "点 $\\mr P$ が直線 $\\mr{AB}$ 上にあるとき，実数 $t$ を用いて次のように表せる．\\begin{align}&\\bect{AP}=t\\bect{AB}.\\\\\\iff& \\bect{OP}=\\bect{OA}+t\\bect{AB}.\\\\\\iff& \\bect{OP}=(1-t)\\bect{OA}+t\\bect{OB}.\\end{align}", canvasScript: "start=[-3, -3]; end=[3, 3]; pointO=[-1, 2]; pointA=[-2, -2]; pointB=[2.5, -2]; pointP=bunten({ between:[pointA, pointB], rate:[3, 2] }); pointMark({ points :[[pointO,'O', [-1, 1]], [pointA, 'A' ,[-1, -2]], [pointB, 'B' ,[0.2, -2]], [pointP, 'P' , [-0.4, -2]] ]}); drawArrow({ from : pointO, to : pointA,size:15, }); drawArrow({ from : pointP, to : pointB,size:15,width:2 }); drawArrow({ from : pointA, to : pointP,size:15,color:'blue',width:2 }); drawArrow({ from : pointO, to : pointP, color : 'red',size:20,width:2 });drawGraph({func:-2});drawHenko({from:pointA,to:pointP,string:'t',circle:true,move:[0,-1]});drawHenko({from:pointA,to:pointB,string:'1',circle:true,angle:35,move:[0,-1]}); "});
